version: "3.8"

services:
  cms-ouvidoria:
    build: ./.docker
    container_name: cms-ouvidoria
    restart: always
    tty: true
    ports:
      - "3333:3333"
    networks:
      - db

networks:
  db:
    driver: bridge
    name: db